name: push
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: ibm-semeru/11-jre
            tag: 11-jre-ibm-semeru
          - path: eclipse-temurin/11-jre
            tag: 11-jre-eclipse-temurin
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{matrix.path}}
          file: ./${{matrix.path}}/Dockerfile
          push: true
          tags: amond/openjdk:${{matrix.tag}}
          platforms: linux/arm64,linux/amd64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
