name: push
on:
  push:
    branches:
      - master
  workflow_dispatch:
    #inputs:
    #  distribution:
    #    default: 'firebase'
    #    description: 'firebase, testflight'
    #    required: true      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./openjdk/11/jre/adopt/ubuntu
          file: ./openjdk/11/jre/adopt/ubuntu/Dockerfile
          push: true
          tags: amond/openjdk:11
          platforms: linux/arm64,linux/amd64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
